#!/usr/bin/env python3
"""
Snapshot the 7DT observation modes for the website.

Reads which filter each unit observes in each mode from the live TCSpy
configuration, and the transmission curve of every filter involved from the
7DT_calculator repository, and writes app/data/obsmodes.json.

Run it again when the modes change:

    python3 scripts/snapshot_obsmodes.py

Why a snapshot rather than a read at request time: the configuration is an NFS
mount from lyman. If lyman is unreachable, a read from it can block, and the
website should not stop serving pages because a telescope-control share is
down. The figure changes when the modes change, which is rarely.

Only filter names are taken from the configuration. The folder also holds
credentials; nothing else in it is read, and nothing from it is copied.
"""
import csv, json, re, sys
from pathlib import Path

CONFIG = Path('/lyman/data1/7dt/configuration')
CURVES = Path('/home/dtak/7DT_calculator/data/transmission')
OUT = Path(__file__).resolve().parent.parent / 'app/data/obsmodes.json'
REMOTE = ('/home/kds/TCSpy/configuration/', '/home/kds/tcspy/configuration/')

BROAD_NM = {'u': 355, 'g': 477, 'r': 623, 'i': 762, 'z': 913}


def local(path_str):
    for prefix in REMOTE:
        if path_str.startswith(prefix):
            return CONFIG / path_str[len(prefix):]
    return Path(path_str)


def folder_of(config_file, key):
    return local(json.loads((CONFIG / config_file).read_text())[key])


def read_mode(path):
    raw = json.loads(Path(path).read_text())
    return {unit: list(filters) for unit, filters in sorted(raw.items())}


def nm(name):
    m = re.match(r'm(\d+)w?$', name)
    return int(m.group(1)) if m else BROAD_NM.get(name)


def curve(name, step=10, floor=0.01):
    """Peak-normalized response on a coarse grid, trimmed to where it is non-zero."""
    rows = list(csv.DictReader(open(CURVES / f'{name}.csv')))
    w = [float(r['wavelength']) for r in rows]
    t = [float(r['response']) for r in rows]
    peak = max(t) or 1.0
    pts = [(round(w[i] / 10, 1), round(t[i] / peak, 3)) for i in range(0, len(w), step)]
    keep = [i for i, (_, v) in enumerate(pts) if v >= floor]
    if not keep:
        return []
    a, b = max(0, keep[0] - 1), min(len(pts), keep[-1] + 2)
    return [list(p) for p in pts[a:b]]          # [nm, response]


def main():
    spec_dir = folder_of('specmode.config', 'SPECMODE_FOLDER')
    color_dir = folder_of('colormode.config', 'COLORMODE_FOLDER')
    spec = read_mode(spec_dir / 'specall.specmode')
    color = read_mode(color_dir / 'gri.colormode')
    units = sorted(spec)

    modes = [
        {
            'key': 'spec', 'name': 'Spec', 'source': f'{spec_dir.name}/specall.specmode',
            'fields': 1, 'example': False,
            'units': spec,
            'note': 'Every unit takes its first filter, then its second: two sets of sixteen, one after the other.',
        },
        {
            'key': 'deep', 'name': 'Deep', 'source': 'example',
            'fields': 1, 'example': True,
            'units': {u: ['r'] for u in units},
            'note': 'Example: all sixteen units through r on one field — the light grasp of a single 2-m aperture. The proposer chooses the filter.',
        },
        {
            'key': 'color', 'name': 'Color', 'source': f'{color_dir.name}/gri.colormode',
            'fields': 1, 'example': False,
            'units': color,
            'note': 'The gri combination: the array split across three broad bands on one field, for simultaneous colors.',
        },
        {
            'key': 'search', 'name': 'Search', 'source': 'example',
            'fields': 16, 'example': True,
            'units': {u: ['r'] for u in units},
            'note': 'Example: each unit on a different, adjacent field through r, covering sixteen fields in one exposure at single-unit depth.',
        },
    ]

    used = sorted({f for m in modes for fs in m['units'].values() for f in fs}, key=lambda n: nm(n) or 0)
    curves = {}
    for f in used:
        if not (CURVES / f'{f}.csv').exists():
            sys.exit(f'no transmission curve for {f}')
        curves[f] = {'nm': nm(f), 'pts': curve(f)}

    out = {
        'note': ('Generated by scripts/snapshot_obsmodes.py from the live TCSpy configuration and the '
                 '7DT_calculator transmission curves. Do not edit by hand; re-run the script.'),
        'units': units,
        'modes': modes,
        'curves': curves,
    }
    OUT.write_text(json.dumps(out, separators=(',', ':')) + '\n')
    print(f'wrote {OUT} — {len(used)} filters, {OUT.stat().st_size / 1024:.1f} kB')


if __name__ == '__main__':
    main()
